add_newline = true

format = "$username$hostname$shlvl$cmd_duration$battery$conda$directory$git_branch$git_status$character"

[character]
success_symbol = "[â¯](#9ece6a)"
error_symbol = "[â¯](#f7768e)"

[directory]
style = "#7aa2f7"
read_only = "î©µ"
read_only_style = '#f7768e'

[git_branch]
style = "#bb9af7"
symbol = "ï˜ "

[git_status]
disabled = false
format = '([\[$all_status$ahead_behind\]]($style) )'
style = 'bold #f7768e'
untracked = "?${count}"
stashed = "ğŸ“¦"
modified = "!${count}"
staged = ""
renamed = ""
deleted = ""
ahead = "â‡¡${count}"
behind = "â‡£${count}"
conflicted = "ó±‹"


[cmd_duration]
min_time = 10_000
format = "î‹ [$duration]($style) "
style = '#e0af68'
show_notifications = false
min_time_to_notify = 30_000

[conda]
symbol = "ğŸ"
style = "#bb9af7"
format = '[$symbol\($environment\)]($style) '

[battery]
format = '[$symbol]($style) '
full_symbol = "ó°¼"
charging_symbol = "ó°‚„"
unknown_symbol = "ó°‚‘"
empty_symbol = "ó°‚"
discharging_symbol = "ó°‚ƒ"

[[battery.display]]
threshold = 25
